import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="container-custom max-w-4xl">
        <div className="mb-6">
          <Button variant="ghost" asChild>
            <Link href="/">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Link>
          </Button>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-border p-8 md:p-12">
          <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mb-8">
            Last updated: {new Date().toLocaleDateString('en-GB')}
          </p>

          <div className="prose prose-blue max-w-none space-y-6">
            <section>
              <h2 className="text-2xl font-semibold mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing or using the Employment Tribunal Documents website ("the Service"), you agree to be bound
                by these Terms of Service. If you do not agree to these terms, you may not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">2. Description of Service</h2>
              <p>
                The Service provides AI-assisted document preparation tools for Employment Tribunal matters in England and Wales.
                The Service includes:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>AI-powered document generation using specialized agents</li>
                <li>Document validation and quality checks</li>
                <li>Downloadable document outputs</li>
              </ul>
            </section>

            <div className="bg-amber-50 border-2 border-amber-500 rounded-lg p-6 my-6">
              <h3 className="text-xl font-bold text-amber-900 mb-4">IMPORTANT LEGAL DISCLAIMERS</h3>

              <div className="space-y-4 text-amber-900">
                <div>
                  <h4 className="font-semibold mb-1">NOT LEGAL ADVICE</h4>
                  <p className="text-sm">
                    This Service does NOT provide legal advice, legal representation, or legal services.
                    The documents generated are for informational purposes only.
                  </p>
                </div>

                <div>
                  <h4 className="font-semibold mb-1">NOT REGULATED PROFESSIONALS</h4>
                  <p className="text-sm">
                    We are NOT solicitors, barristers, or regulated legal professionals.
                    We are NOT regulated by the Solicitors Regulation Authority (SRA) or Bar Standards Board (BSB).
                  </p>
                </div>

                <div>
                  <h4 className="font-semibold mb-1">NO SOLICITOR-CLIENT RELATIONSHIP</h4>
                  <p className="text-sm">
                    Using this Service does NOT create a solicitor-client relationship, attorney-client privilege,
                    or any confidential relationship.
                  </p>
                </div>

                <div>
                  <h4 className="font-semibold mb-1">SEEK PROFESSIONAL ADVICE</h4>
                  <p className="text-sm">
                    You MUST consult a qualified solicitor for legal advice specific to your situation.
                    Do NOT rely solely on AI-generated documents for legal proceedings.
                  </p>
                </div>
              </div>
            </div>

            <section>
              <h2 className="text-2xl font-semibold mb-3">3. User Obligations</h2>
              <p>
                By using the Service, you agree to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Provide accurate information</li>
                <li>Use the Service only for lawful purposes</li>
                <li>Not upload malicious files or content</li>
                <li>Not attempt to circumvent security measures</li>
                <li>Not misrepresent the nature of the Service to others</li>
                <li>Seek professional legal advice before using any generated documents</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">4. Intellectual Property</h2>
              <p>
                <strong>Your Content:</strong> You retain all rights to documents you upload. We do not claim ownership.
              </p>
              <p>
                <strong>Generated Documents:</strong> Documents generated by the Service are provided to you for your use.
                We do not claim ownership of the output.
              </p>
              <p>
                <strong>The Service:</strong> The Service itself, including all software, code, and design, is protected by copyright and other intellectual property laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">5. Limitation of Liability</h2>
              <div className="bg-red-50 border border-red-200 rounded-lg p-4 my-4">
                <p className="text-sm text-red-900">
                  <strong>IMPORTANT:</strong> Please read this section carefully.
                </p>
              </div>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>The Service is provided "AS IS" without warranties of any kind</li>
                <li>We make no guarantees about accuracy, completeness, or fitness for purpose</li>
                <li>We are NOT liable for any damages arising from use of the Service</li>
                <li>We are NOT liable for errors or omissions in generated documents</li>
                <li>We are NOT liable for outcomes in legal proceedings</li>
                <li>Your use of the Service is at your own risk</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">6. Disclaimer of Warranties</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>We do not warrant that the Service will be uninterrupted or error-free</li>
                <li>We do not warrant that documents will be accurate or suitable for your needs</li>
                <li>We do not warrant that the Service will meet your requirements</li>
                <li>AI-generated content may contain errors, omissions, or inaccuracies</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">7. Jurisdiction and Applicable Law</h2>
              <p>
                These Terms are governed by the laws of England and Wales. The Service is intended for use in
                Employment Tribunal matters in England and Wales only.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">8. Data and Privacy</h2>
              <p>
                Your use of the Service is subject to our
                <Link href="/privacy" className="text-primary hover:underline ml-1">Privacy Policy</Link>.
                By using the Service, you consent to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Temporary processing of your uploaded files</li>
                <li>Use of third-party AI services (Anthropic Claude) to process documents</li>
                <li>Immediate deletion of files after processing</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">9. Prohibited Uses</h2>
              <p>
                You may NOT use the Service to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Obtain legal advice (consult a solicitor instead)</li>
                <li>Replace professional legal representation</li>
                <li>Upload confidential or privileged documents without appropriate safeguards</li>
                <li>Violate any laws or regulations</li>
                <li>Infringe on others' rights</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">10. Service Modifications and Termination</h2>
              <p>
                We reserve the right to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Modify or discontinue the Service at any time</li>
                <li>Refuse service to anyone for any reason</li>
                <li>Change these Terms at any time (changes posted on this page)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">11. No Professional Relationship</h2>
              <p>
                Using this Service does NOT create any professional relationship between you and us.
                We owe you no professional duties. We are not acting on your behalf.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">12. Indemnification</h2>
              <p>
                You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any laws or third-party rights</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">13. Contact</h2>
              <p>
                For questions about these Terms, visit our
                <Link href="/support" className="text-primary hover:underline ml-1">Support page</Link>.
              </p>
            </section>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mt-8">
              <h3 className="font-semibold mb-3">Summary (NOT a substitute for reading the full terms)</h3>
              <ul className="text-sm space-y-2">
                <li>✓ This is NOT legal advice or a legal service</li>
                <li>✓ We are NOT solicitors or regulated professionals</li>
                <li>✓ You MUST consult a qualified solicitor</li>
                <li>✓ Use at your own risk - no warranties</li>
                <li>✓ We're not liable for errors or outcomes</li>
                <li>✓ Files deleted immediately after processing</li>
                <li>✓ England & Wales jurisdiction only</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
